### ISSUE TITLE
Prevent loading new track/tournament if some rounds have been ran

### ISSUE THREAD

**Issue by Pimentoso** [Pimentoso/mini4wdchrono#44]
It might be a good idea to block the user from reloading a new track or tournament if some rounds have been played. It would mess up everything. The user should be forced to use the 'new race' button and reset everything.

**Comment by Pimentoso** [comment]
Fixed in #46

**Comment by markinNZ** [comment]
Hi Michele
I'm attempting a build of the mini4wd chrono for our local club and I have
some questions.  I have some basic understanding of electronics, but I need
clarification on the wiring diagram.

1) please confirm - resistors on the green LEDs are 220 ohm

2) the Photo sensor TEMT6000 has 3 connections.  In the photos I can see 3
wires going to it, but on the circuit diagram there are only 2 and it does
not say where to connect them - OUT, GND or VCC

3) is the resistor for the photo sensor 10K ohm? Is that right for the
TEMT6000 and which of the 3 connections is it connected to?

4) what are the green LEDs for?  I can't see reference to them in the
documentation.  Do they turn on to start the race?

5) I've got the laser diodes.  I guess that these are powered the whole
time.  Can I plug these straight into the 5v power pin on the arduino?  Do
I need any resistors inline with these?

thanks for your help.

We're excited to have this running for our races.

thanks

Mark (from New Zealand)

**Comment by Pimentoso** [comment]
Hi Mark, I moved your comment to a new issue. Please check my reply here --> #47

**Comment by bahrien** [comment]
how i want to comment,
